{{- if .Values.secret.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.secretName }}
  labels:
    app: backend
    app.kubernetes.io/name: deploycart-backend
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: Helm
type: Opaque
stringData:
  MONGO_URI: {{ .Values.secret.data.MONGO_URI | quote }}
  PORT: {{ .Values.secret.data.PORT | quote }}
  NODE_ENV: {{ .Values.secret.data.NODE_ENV | quote }}
  ENABLE_CONSOLE_LOGS: {{ .Values.secret.data.ENABLE_CONSOLE_LOGS | quote }}
  JWT_SECRET: {{ .Values.secret.data.JWT_SECRET | quote }}
  ACCESS_TOKEN_SECRET: {{ .Values.secret.data.ACCESS_TOKEN_SECRET | quote }}
  REFRESH_TOKEN_SECRET: {{ .Values.secret.data.REFRESH_TOKEN_SECRET | quote }}
  EMAIL_HOST: {{ .Values.secret.data.EMAIL_HOST | quote }}
  EMAIL_PORT: {{ .Values.secret.data.EMAIL_PORT | quote }}
  EMAIL_USER: {{ .Values.secret.data.EMAIL_USER | quote }}
  EMAIL_PASS: {{ .Values.secret.data.EMAIL_PASS | quote }}
  CLOUDINARY_CLOUD_NAME: {{ .Values.secret.data.CLOUDINARY_CLOUD_NAME | quote }}
  CLOUDINARY_API_KEY: {{ .Values.secret.data.CLOUDINARY_API_KEY | quote }}
  CLOUDINARY_API_SECRET: {{ .Values.secret.data.CLOUDINARY_API_SECRET | quote }}
{{- end }}