apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: deploycart-backend
  namespace: argocd

  finalizers:
    - resources-finalizer.argocd.argoproj.io

  annotations:
    argocd-image-updater.argoproj.io/image-list: "backend=797601397904.dkr.ecr.us-east-1.amazonaws.com/backend"

    argocd-image-updater.argoproj.io/backend.update-strategy: "semver"
    argocd-image-updater.argoproj.io/backend.allow-tags: 'regexp:^v[0-9]+\.[0-9]+\.[0-9]+$'

    argocd-image-updater.argoproj.io/backend.helm.image-name: "image.repository"
    argocd-image-updater.argoproj.io/backend.helm.image-tag: "image.tag"

    argocd-image-updater.argoproj.io/backend.force-update: "true"
    argocd-image-updater.argoproj.io/write-back-method: "argocd"

spec:
  project: default

  source:
    repoURL: "https://github.com/Filopateer-Shaker/Deploy-Cart.git"
    targetRevision: main
    path: helm/backend

    helm:
      releaseName: backend

      valueFiles:
        - values.yaml

      parameters:
        - name: image.repository
          value: "797601397904.dkr.ecr.us-east-1.amazonaws.com/backend"

        - name: image.tag
          value: "v0.0.40"

        - name: autoscaling.enabled
          value: "false"

  destination:
    server: "https://kubernetes.default.svc"
    namespace: backend

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

    syncOptions:
      - CreateNamespace=true