replicaCount: 1

image:
  repository: 797601397904.dkr.ecr.us-east-1.amazonaws.com/frontend
  tag: v0.0.53
  pullPolicy: IfNotPresent

containerPort: 80

service:
  type: ClusterIP
  port: 80
  targetPort: 80

ingress:
  enabled: true
  className: nginx
  host: ""
  path: /
  pathType: Prefix

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 300m
    memory: 256Mi


readinessProbe:
  enabled: true
  path: /
  initialDelaySeconds: 10
  periodSeconds: 10

livenessProbe:
  enabled: true
  path: /
  initialDelaySeconds: 20
  periodSeconds: 20

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 70

serviceAccount:
  create: true
  name: frontend-sa
  automountServiceAccountToken: false
